[EMAIL_SETTINGS]

# Separate recipients with semicolons

recipients = joe.bloggs@example.com
cc_recipients = finance.manager@example.com; finance.team@example.com

subject = Latest sales report attached

[EMAIL_CONTENT]

# The email body can contain multiple lines.Indent additional lines to keep them as part of the body.

body = Hi Team,

    The latest sales report is attached.

    If you have any questions, please let me know.

    Kind Regards,
    The Bakery Shop


[EXCEL_REPORT_FORMATTING]

# Separate multiple files (if have multiple) with semicolons
attachment_paths = C:\Users\your_username\Documents\Sales\sales_data.xlsx

sheet_name = Sales
bold_header = True
italic_font = True

# RGB colour: (Red, Green, Blue)
# Example: light pink
heading_colour = (241, 214, 236)
