[EMAIL_SETTINGS]
# separate recipients with semi colons
recipients = finance-team@bakery.com; Joe-Bloggs@bakery.com
cc_recipients = finance-manager@bakery.com; Jane_Doe@bakery.com
subject = Latest sales report attached

[EMAIL_CONTENT]
# Can write as many lines as want, as long as indent them (needs to keep indent)
body =Hi Team,

	The latest sales report is attached.

	If you have any questions please let me know.

	Kind Regards,
	The Bakery team

[EXCEL_REPORT_FORMATTING]
# separate files with semi colons
attachment_paths = C:\Users\Sean Redmond\Documents\Cake_Shop_Dummy_Sales_Data.xlsx; C:\Users\Sean Redmond\Documents\Bakery report template (test that can send multiple attachments in project).xlsx
sheet_name = Sales
bold_header = True
italic_font = True

# can change to different RGB Colour code - can find values online
heading_colour = (241, 214, 236)