[EMAIL_SETTINGS]
recipients = a@gmail.com, b@gmail.com
cc_recipients = c@gmail.com
subject = I'm sending an outlook email

[EMAIL_CONTENT]
# Can write as many lines as want, as long as indent them (needs to keep indent)
body =Hi Team,

	I want to send a message using outlook!

	Kind Regards,
	Sean

[EXCEL_REPORT_FORMATTING]
file_location = C:\Users\Sean Redmond\Documents\Cake_Shop_Dummy_Sales_Data.xlsx
sheet_name = Sales
bold_header = True
italic_first_five_rows = True

# can change to different RGB Colour code - can find values online
line_two_to_five_colour = (128, 0, 128)
heading_colour = (241, 214, 236)